name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-and-analysis:
    name: Tests and Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, tokenizer, pdo_mysql, pdo_sqlite

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          # Cache Composer dependencies to speed up workflow
          path: ~/.composer/cache
          # Calcule une clé de cache basée sur le fichier composer.lock
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
